### ISSUE TITLE
LeP Bearbeiten

### ISSUE THREAD

**Issue by TimPatrickProgramming** [Jave01/BDSM#2]
Es wäre ein Tolles Feature, wenn im BDSM Tool selbst die Maximalen Lebenspunkte noch angepasst werden können.
Heist das die Maximalen LeP von Bsp. 30 erhöht werden kann. Beispielsweise um 10 LeP, so das am Ende die Max LeP 40 Betragen.
Dabei müsste man evtl. die mit AP dazugekauften LeP mit berücksichtigt werden. So das am Ende, die Berechneten LeP aus KO Wert, die mit AP dazugekauften LeP und die im BDSM Tool hinzugefügten LeP zusammengerechnet werden.

**Comment by A5t4t1ne** [comment]
Die mit AP dazu dazugekauften LeP sollten eigentlich berücksichtigt werden (beim heraufladen des Helden) aber die Anpassung der max LeP nehme ich zur Kenntniss.
